### PR TITLE
GUI-Python3 implementation working properly

### PR DESCRIPTION
**Pull request by maniotrix**

### CODE REVIEW

**Comment by cristobalmedinalopez** [comment]
Hi @maniotrix, When I try to run `python3 p2psp_application_gui.py` I get this error: `Segmentation fault (core dumped)`. Any idea? 

Thanks!

**Comment by maniotrix** [comment]
Hi @cristobalmedinalopez 

Here is the screenshot of git log on  gui branch of my fork:
screenshot from 2016-03-06 08-21-59

Here is the video of working of python3 GUI:
[Python3 GUI](https://www.youtube.com/watch?v=FsFteDz1byE&feature=youtu.be)

I am not experiencing this issue on my machine. And currently I have no idea why you are having such problem.

Did you have this issue earlier?

**Comment by cristobalmedinalopez** [comment]
Hi @maniotrix,

I can see that it works perfectly for you (thanks for share it). However, I tried it in three different machines, all of them running Ubuntu with GNOME. it didn't work :_(
I'll continue investigating...

**Comment by cristobalmedinalopez** [comment]
Hi again!

I found the problem. It's the thumbnail_url field in the saved_channels file. The image is not found in my system and it crashs (Is it possible to use a relative path?). If the file is deleted, it works fine. However, when I try with another Splitter IP, it doesn't work. It always tries to connect with loopback IP. I thought that it was resolved some time ago...

Thanks!

**Comment by maniotrix** [comment]
Hi @cristobalmedinalopez 
The thumbnail image should be absolute path.Helpful if thumbnail is located at a remote location.What do you suggest?
About Spliiter IP problem, the second last commit on this PR would solve the issue.
I have also removed the saved_channels file for now.

Thanks.

**Comment by cristobalmedinalopez** [comment]
Thanks @maniotrix!

A remote location is a good idea but maybe it should be downloaded the first time and save it into a local location for future uses. 

Why is not possible to use a relative path?

**Comment by maniotrix** [comment]
Hi @cristobalmedinalopez 

Yes, if a remote location is provided, we have to first download that and can save locally for future uses.And if user changes url of image,previous can be replaced with the latter.

**Pull request merged**
