### PR TITLE
GUI-Python3 implementation working properly 

### PR DESCRIPTION
**Pull request by maniotrix**

### CODE REVIEW

**Comment by cristobalmedinalopez** [comment]
Thanks @maniotrix

We are going to wait before merging because this version modifies some files of the core. We are working in a c++ version of the core that is almost finished. We are merging your changes in the new version.

Happy New Year! :-D

**Comment by cristobalmedinalopez** [comment]
Hi @maniotrix,

Would be possible to move this PR to gui branch?

**Comment by maniotrix** [comment]
Hi @cristobalmedinalopez 

Yes I have created a PR which can be merged in p2psp/gui branch

**Comment by cristobalmedinalopez** [comment]
This was merged in the gui branch.

**Pull request closed without merging**
