### PR TITLE
channel window visibility can be toggled and  stream played

### PR DESCRIPTION
**Pull request by maniotrix**
### Please run `src/p2psp_application_gui` to review the current status of gui.
screenshot from 2015-06-02 23 49 14

screenshot from 2015-06-02 23 51 38

#### currently known issues:
* Player/Status Box does not hide after fullscreen(although this issue will be resolved in next commit)
* no key-bindings anywhere in the application.
* obviously thumbnail has to be  resized.
* proper documentation will be also done in  next commit.
* channel display box is not fully functional currently.

### CODE REVIEW

**Comment by josejuansanchez** [comment]
Hi @maniotrix! 

I think could be great to have the source code files organized in another way.

This is my **proposal for the directory structure**:

```
src
	- mainapplication.py

	- core
		- peer.py
		- splitter.py
		- ...

	- gui
		- vlc.py
		- ...

data
	-  glade
		- mainwindow.glade
		- ...
	- images
		- logo.png
		- ...
```

The `src` directory would contain a `mainapplication.py` file and the directories: `core` (the current source code for the protocol) and `gui` (the code related with the desktop app).

Furthermore, the resources (e.g. images) and .glade files would be located in the `data` directory.

Finally, I think that the file `P2PSP_GUI.glade~` should not be included in the commit.

@maniotrix @vicente-gonzalez-ruiz @cristobalmedinalopez What do you think about this proposal?

**Comment by maniotrix** [comment]
Sorry for adding `P2PSP_GUI.glade~` .I should have not included it for tracking.

**Comment by maniotrix** [comment]
@josejuansanchez :+1:

**Comment by maniotrix** [comment]
Although Player/Status  box gets hidden on player fullscreen , but mouse pointer disappears when it moves to player area(with or without fullscreen). I have tried but couldn't find a solution to this problem.

**Comment by josejuansanchez** [comment]
@maniotrix Don't worry about it. We can open an issue and try to fix later.

**Comment by josejuansanchez** [comment]
@maniotrix Do you mind to file a pull request over the **`gui`** branch?
I had to revert the previous pull request (#13) because this was filed over the **`master`** branch. Sorry.

**Pull request merged**
