### PR TITLE
Added DoxyFile and Player's Surface key events and altered play button functionality

### PR DESCRIPTION
**Pull request by maniotrix**

### CODE REVIEW

**Comment by maniotrix** [comment]
closes #54

**Comment by josejuansanchez** [comment]
@maniotrix I suggest to rename the Doxygen config file from `doxy_config` to `doxygen.cfg` and place it inside the doc folder.

Another suggestion is that I think is not a good idea to store the Doxygen HTML documentation in the repository.

I think we should find another solution to be able to keep the documentation updated.

**Comment by maniotrix** [comment]
Ok Doxygen config file will be renamed.

**Comment by maniotrix** [comment]
One solution would be to use github pages to host documentation.

**Comment by maniotrix** [comment]
I have updated player surface with key press events in place of mouse events. It is done according to the proposal which I mentioned in #15 issue.

**Comment by josejuansanchez** [comment]
Good work!

**Pull request merged**
